import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

const categoriesData = [
  { id: "mirrorless", name: "กล้อง Mirrorless", icon: "📷" },
  { id: "pocket-camera", name: "กล้องพกพา", icon: "🎥" },
  { id: "lens", name: "เลนส์", icon: "🔍" },
  { id: "cinema-lens", name: "เลนส์ซีนีม่า", icon: "🎬" },
  { id: "gimbal", name: "กิมบอล", icon: "🧷" },
  { id: "monitor", name: "จอมอนิเตอร์", icon: "🖥️" },
  { id: "light", name: "ไฟถ่ายภาพ/วิดีโอ", icon: "💡" },
  { id: "tripod", name: "ขาตั้งกล้อง", icon: "🦾" },
  { id: "rig-accessory", name: "ริก/อุปกรณ์เสริม", icon: "🎒" },
  { id: "communication", name: "วิทยุสื่อสาร", icon: "📻" },
  { id: "bundle-set", name: "เซ็ตครบชุด", icon: "🎁" },
];

const brandsData = [
  { id: "sony", name: "Sony", logo: "SONY" },
  { id: "fujifilm", name: "Fujifilm", logo: "FUJIFILM" },
  { id: "dji", name: "DJI", logo: "DJI" },
  { id: "tilta", name: "Tilta", logo: "TILTA" },
  { id: "feelworld", name: "Feelworld", logo: "FEELWORLD" },
  { id: "samyang", name: "Samyang", logo: "SAMYANG" },
  { id: "viltrox", name: "Viltrox", logo: "VILTROX" },
  { id: "ttartisan", name: "TTArtisan", logo: "TTArtisan" },
  { id: "sirui", name: "SIRUI", logo: "SIRUI" },
  { id: "smallrig", name: "SmallRig", logo: "SmallRig" },
  { id: "nanlite", name: "Nanlite", logo: "NANLITE" },
  { id: "amaran", name: "Amaran (Aputure)", logo: "amaran" },
  { id: "neewer", name: "Neewer", logo: "NEEWER" },
  { id: "motorola", name: "Motorola", logo: "MOTOROLA" },
  { id: "hollyland", name: "Hollyland", logo: "HOLLYLAND" },
  { id: "atomos", name: "Atomos", logo: "ATOMOS" },
  { id: "plu", name: "ร้าน Plu For Rent", logo: "PLU" },
];

const productsData = [
  {
    id: "sony-fx30-body",
    name: "Sony FX30 (Body Only)",
    brandId: "sony",
    categoryId: "mirrorless",
    pricePerDay: 1000,
    deposit: 0,
    image: "/products/sony-fx30-body.jpg",
    rating: 4.8,
    reviewCount: 0,
    available: true,
    published: true,
    description: "กล้อง Sony Cinema Line FX30 ตัวเปล่า เซนเซอร์ APS-C 4K(QFHD) เหมาะสำหรับงานวิดีโอระดับมืออาชีพ",
    specs: [
      { label: "เซนเซอร์", value: "APS-C high-sensitivity CMOS" },
      { label: "วิดีโอ", value: "4K (QFHD)" },
      { label: "มาวด์", value: "Sony E-mount" },
    ],
    includes: ["ตัวกล้อง"],
  },
  {
    id: "sony-a6600",
    name: "Sony A6600",
    brandId: "sony",
    categoryId: "mirrorless",
    pricePerDay: 750,
    deposit: 0,
    image: "/products/sony-a6600.jpg",
    rating: 4.7,
    reviewCount: 0,
    available: true,
    published: true,
    description: "กล้อง Sony A6600 พร้อมแบตเตอรี่และเมมโมรี่การ์ด เพิ่มแบตเตอรี่อีก 2 ก้อน +100 บาท/วัน",
    specs: [
      { label: "เซนเซอร์", value: "APS-C" },
      { label: "มาวด์", value: "Sony E-mount" },
    ],
    includes: ["ตัวกล้อง", "แบตเตอรี่ 1 ก้อน", "เมมโมรี่การ์ด 1 ใบ"],
  },
  {
    id: "sony-a6400",
    name: "Sony A6400",
    brandId: "sony",
    categoryId: "mirrorless",
    pricePerDay: 600,
    deposit: 0,
    image: "/products/sony-a6400.jpg",
    rating: 4.6,
    reviewCount: 0,
    available: true,
    published: true,
    description: "กล้อง Sony A6400 พร้อมแบตเตอรี่ 4 ก้อนและเมมโมรี่การ์ด",
    specs: [
      { label: "เซนเซอร์", value: "APS-C" },
      { label: "มาวด์", value: "Sony E-mount" },
    ],
    includes: ["ตัวกล้อง", "แบตเตอรี่ 4 ก้อน", "เมมโมรี่การ์ด 1 ใบ"],
  },
  {
    id: "fujifilm-x-half",
    name: "Fujifilm X-half",
    brandId: "fujifilm",
    categoryId: "mirrorless",
    pricePerDay: 600,
    deposit: 0,
    image: "/products/fujifilm-x-half.jpg",
    rating: 4.8,
    reviewCount: 0,
    available: true,
    published: true,
    description: "กล้อง Fujifilm X-half ดีไซน์คลาสสิก พร้อมแบตเตอรี่และเมมโมรี่การ์ด",
    specs: [{ label: "เลนส์", value: "Fujinon Aspherical f=10.8mm f/2.8" }],
    includes: ["ตัวกล้อง", "แบตเตอรี่ 1 ก้อน", "เมมโมรี่การ์ด 1 ใบ"],
  },
  {
    id: "tilta-set-rig",
    name: "Tilta Set Rig (FX3/FX30)",
    brandId: "tilta",
    categoryId: "rig-accessory",
    pricePerDay: 300,
    deposit: 0,
    image: "/products/tilta-set-rig.jpg",
    rating: 4.7,
    reviewCount: 0,
    available: true,
    published: true,
    description: "ชุดริก Tilta สำหรับกล้อง Sony FX3/FX30 เพิ่มความสะดวกในการถือถ่าย",
    specs: [{ label: "รองรับกล้อง", value: "Sony FX3 / FX30" }],
    includes: ["เคจสำหรับ FX3/FX30", "อุปกรณ์ยึดจับ"],
  },
  {
    id: "tilta-mini-follow-focus",
    name: "Tilta Mini Pocket Follow Focus",
    brandId: "tilta",
    categoryId: "rig-accessory",
    pricePerDay: 50,
    deposit: 0,
    image: "/products/tilta-mini-follow-focus.jpg",
    rating: 4.6,
    reviewCount: 0,
    available: true,
    published: true,
    description: "Follow Focus ขนาดพกพาจาก Tilta ใช้งานง่าย ติดตั้งเร็ว",
    specs: [],
    includes: [],
  },
  {
    id: "dji-ronin-rsc2-pro",
    name: "DJI Ronin RSC2 Pro Combo",
    brandId: "dji",
    categoryId: "gimbal",
    pricePerDay: 400,
    deposit: 0,
    image: "/products/dji-ronin-rsc2-pro.jpg",
    rating: 4.9,
    reviewCount: 0,
    available: true,
    published: true,
    description: "กิมบอล DJI Ronin RSC2 Pro Combo รับน้ำหนักได้ถึง 3kg เสถียรทุกการเคลื่อนไหว",
    specs: [{ label: "รับน้ำหนักสูงสุด", value: "3kg" }],
    includes: ["ตัวกิมบอล", "อุปกรณ์เสริมชุด Pro Combo", "กระเป๋าใส่"],
  },
  {
    id: "dji-osmo-pocket3",
    name: "DJI Osmo Pocket 3 [Full Set]",
    brandId: "dji",
    categoryId: "pocket-camera",
    pricePerDay: 600,
    deposit: 0,
    image: "/products/dji-osmo-pocket3.jpg",
    rating: 4.8,
    reviewCount: 0,
    available: true,
    published: true,
    description: "DJI Osmo Pocket 3 ชุดเต็มพร้อมอุปกรณ์เสริมครบครัน",
    specs: [],
    includes: [
      "ตัวกล้อง",
      "เลนส์ไวด์",
      "DJI Mic 2 (ตัวส่ง)",
      "ที่กันลม",
      "คลิปแม่เหล็ก",
      "สาย PD",
      "สายคล้องมือ",
      "เคสป้องกัน",
      "ด้ามจับ",
      "กระเป๋าใส่อุปกรณ์",
      "ด้ามแบตเตอรี่",
      "ขาตั้งมินิ",
    ],
  },
  {
    id: "feelworld-f5-pro-v4",
    name: "Feelworld F5 Pro V4 Monitor",
    brandId: "feelworld",
    categoryId: "monitor",
    pricePerDay: 200,
    deposit: 0,
    image: "/products/feelworld-f5-pro-v4.jpg",
    rating: 4.6,
    reviewCount: 0,
    available: true,
    published: true,
    description: "จอมอนิเตอร์ Feelworld F5 Pro V4 สำหรับตรวจสอบภาพหน้างาน",
    specs: [],
    includes: [],
  },
  {
    id: "samyang-af-35-1.8",
    name: "Samyang AF 35mm F1.8 FE",
    brandId: "samyang",
    categoryId: "lens",
    pricePerDay: 250,
    deposit: 0,
    image: "/products/samyang-af-35-1.8.jpg",
    rating: 4.7,
    reviewCount: 0,
    available: true,
    published: true,
    description: "เลนส์ออโต้โฟกัส Samyang AF 35mm F1.8 FE คมชัด น้ำหนักเบา",
    specs: [{ label: "ระยะโฟกัส", value: "35mm" }, { label: "รูรับแสง", value: "F1.8" }],
    includes: ["ตัวเลนส์", "ฝาหน้า-หลัง"],
  },
  {
    id: "viltrox-af-9-2.8",
    name: "Viltrox AF 9mm F2.8 APS-C",
    brandId: "viltrox",
    categoryId: "lens",
    pricePerDay: 250,
    deposit: 0,
    image: "/products/viltrox-af-9-2.8.jpg",
    rating: 4.6,
    reviewCount: 0,
    available: true,
    published: true,
    description: "เลนส์ออโต้โฟกัส Viltrox AF 9mm F2.8 APS-C มุมกว้างพิเศษ",
    specs: [{ label: "ระยะโฟกัส", value: "9mm" }, { label: "รูรับแสง", value: "F2.8" }],
    includes: ["ตัวเลนส์", "ฝาหน้า-หลัง"],
  },
  {
    id: "ttartisan-fisheye-7.5-2",
    name: "TTArtisan APS-C 7.5mm F2 Fisheye (Manual Focus)",
    brandId: "ttartisan",
    categoryId: "lens",
    pricePerDay: 200,
    deposit: 0,
    image: "/products/ttartisan-fisheye-7.5-2.jpg",
    rating: 4.5,
    reviewCount: 0,
    available: true,
    published: true,
    description: "เลนส์ฟิชอาย TTArtisan 7.5mm F2 โฟกัสแมนนวล ถ่ายได้ทั้งแบบ Diagonal และ Circular Fisheye",
    specs: [{ label: "ระยะโฟกัส", value: "7.5mm" }, { label: "รูรับแสง", value: "F2" }],
    includes: ["ตัวเลนส์", "ฝาหน้า-หลัง"],
  },
  {
    id: "sirui-sniper-1lens",
    name: "SIRUI Sniper F1.2 APS-C (1 เลนส์)",
    brandId: "sirui",
    categoryId: "lens",
    pricePerDay: 300,
    deposit: 0,
    image: "/products/sirui-sniper-1lens.jpg",
    rating: 4.8,
    reviewCount: 0,
    available: true,
    published: true,
    description: "เลนส์ออโต้โฟกัส SIRUI Sniper F1.2 APS-C เลือกได้ 16mm / 23mm / 33mm / 56mm",
    specs: [{ label: "รูรับแสง", value: "F1.2" }],
    includes: ["ตัวเลนส์", "ฝาหน้า-หลัง"],
  },
  {
    id: "sirui-sniper-4lens-set",
    name: "SIRUI Sniper F1.2 APS-C (เซ็ต 4 เลนส์)",
    brandId: "sirui",
    categoryId: "lens",
    pricePerDay: 1000,
    deposit: 0,
    image: "/products/sirui-sniper-4lens-set.jpg",
    rating: 4.9,
    reviewCount: 0,
    available: true,
    published: true,
    description: "ชุดเลนส์ SIRUI Sniper F1.2 APS-C ครบทั้ง 4 ทางยาวโฟกัส",
    specs: [{ label: "รูรับแสง", value: "F1.2" }],
    includes: ["เลนส์ 16mm", "เลนส์ 23mm", "เลนส์ 33mm", "เลนส์ 56mm"],
  },
  {
    id: "sirui-nightwalker-1lens",
    name: "SIRUI Night Walker T1.2 Cinema (1 เลนส์)",
    brandId: "sirui",
    categoryId: "cinema-lens",
    pricePerDay: 300,
    deposit: 0,
    image: "/products/sirui-nightwalker-1lens.jpg",
    rating: 4.8,
    reviewCount: 0,
    available: true,
    published: true,
    description: "เลนส์ซีนีม่า SIRUI Night Walker T1.2 โฟกัสแมนนวล เลือกได้ 24mm / 35mm / 56mm",
    specs: [{ label: "รูรับแสง", value: "T1.2" }],
    includes: ["ตัวเลนส์"],
  },
  {
    id: "sirui-nightwalker-2lens",
    name: "SIRUI Night Walker T1.2 Cinema (2 เลนส์)",
    brandId: "sirui",
    categoryId: "cinema-lens",
    pricePerDay: 500,
    deposit: 0,
    image: "/products/sirui-nightwalker-2lens.jpg",
    rating: 4.8,
    reviewCount: 0,
    available: true,
    published: true,
    description: "เลนส์ซีนีม่า SIRUI Night Walker T1.2 เลือกได้ 2 ทางยาวโฟกัสจาก 24mm / 35mm / 56mm",
    specs: [{ label: "รูรับแสง", value: "T1.2" }],
    includes: ["เลนส์ 2 ตัว"],
  },
  {
    id: "sirui-nightwalker-3lens-set",
    name: "SIRUI Night Walker T1.2 Cinema (เซ็ต 3 เลนส์)",
    brandId: "sirui",
    categoryId: "cinema-lens",
    pricePerDay: 700,
    deposit: 0,
    image: "/products/sirui-nightwalker-3lens-set.jpg",
    rating: 4.9,
    reviewCount: 0,
    available: true,
    published: true,
    description: "ชุดเลนส์ซีนีม่า SIRUI Night Walker T1.2 ครบทั้ง 3 ทางยาวโฟกัส",
    specs: [{ label: "รูรับแสง", value: "T1.2" }],
    includes: ["เลนส์ 24mm T1.2", "เลนส์ 35mm T1.2", "เลนส์ 56mm T1.2"],
  },
  {
    id: "smallrig-vmount-vb99",
    name: "SmallRig V-Mount VB99 Battery",
    brandId: "smallrig",
    categoryId: "rig-accessory",
    pricePerDay: 150,
    deposit: 0,
    image: "/products/smallrig-vmount-vb99.jpg",
    rating: 4.7,
    reviewCount: 0,
    available: true,
    published: true,
    description: "แบตเตอรี่ V-Mount SmallRig VB99 ความจุสูง ใช้งานได้ยาวนาน",
    specs: [],
    includes: [],
  },
  {
    id: "nanlite-pavotube-1tube",
    name: "Nanlite Pavotube (1 แท่ง)",
    brandId: "nanlite",
    categoryId: "light",
    pricePerDay: 200,
    deposit: 0,
    image: "/products/nanlite-pavotube-1tube.jpg",
    rating: 4.6,
    reviewCount: 0,
    available: true,
    published: true,
    description: "ไฟหลอด Nanlite Pavotube ปรับสีได้ พกพาสะดวก",
    specs: [],
    includes: [],
  },
  {
    id: "nanlite-pavotube-2tube-set",
    name: "Nanlite Pavotube (เซ็ต 2 แท่ง)",
    brandId: "nanlite",
    categoryId: "light",
    pricePerDay: 300,
    deposit: 0,
    image: "/products/nanlite-pavotube-2tube-set.jpg",
    rating: 4.7,
    reviewCount: 0,
    available: true,
    published: true,
    description: "ไฟหลอด Nanlite Pavotube เซ็ตคู่ ปรับสีได้ พกพาสะดวก",
    specs: [],
    includes: ["Nanlite Pavotube x2"],
  },
  {
    id: "amaran-300c-set",
    name: "Amaran 300c + Stand + Softbox",
    brandId: "amaran",
    categoryId: "light",
    pricePerDay: 500,
    deposit: 0,
    image: "/products/amaran-300c-set.jpg",
    rating: 4.8,
    reviewCount: 0,
    available: true,
    published: true,
    description: "ไฟ Amaran 300c พร้อมขาตั้ง (เลือกขาตั้งไฟหรือขาตั้ง C) และ softbox (เลือก mini dome หรือ Softbox Lantern)",
    specs: [],
    includes: ["Amaran 300c", "ขาตั้งไฟ/ขาตั้ง C", "Softbox"],
  },
  {
    id: "amaran-150c-set",
    name: "Amaran 150c + Stand + Softbox",
    brandId: "amaran",
    categoryId: "light",
    pricePerDay: 400,
    deposit: 0,
    image: "/products/amaran-150c-set.jpg",
    rating: 4.7,
    reviewCount: 0,
    available: true,
    published: true,
    description: "ไฟ Amaran 150c พร้อมขาตั้ง (เลือกขาตั้งไฟหรือขาตั้ง C) และ softbox (เลือก mini dome หรือ Softbox Lantern)",
    specs: [],
    includes: ["Amaran 150c", "ขาตั้งไฟ/ขาตั้ง C", "Softbox"],
  },
  {
    id: "amaran-60xs-set",
    name: "Amaran 60x-S + Stand + Softbox",
    brandId: "amaran",
    categoryId: "light",
    pricePerDay: 300,
    deposit: 0,
    image: "/products/amaran-60xs-set.jpg",
    rating: 4.6,
    reviewCount: 0,
    available: true,
    published: true,
    description: "ไฟ Amaran 60x-S พร้อมขาตั้ง (เลือกขาตั้งไฟหรือขาตั้ง C) และ softbox (เลือก mini dome หรือ Softbox Lantern)",
    specs: [],
    includes: ["Amaran 60x-S", "ขาตั้งไฟ/ขาตั้ง C", "Softbox"],
  },
  {
    id: "neewer-matte-box-nd-kit",
    name: "Neewer Mini Matte Box PG002 + ND Filter Kit",
    brandId: "neewer",
    categoryId: "rig-accessory",
    pricePerDay: 150,
    deposit: 0,
    image: "/products/neewer-matte-box-nd-kit.jpg",
    rating: 4.5,
    reviewCount: 0,
    available: true,
    published: true,
    description: "Matte Box Neewer PG002 พร้อมชุดฟิลเตอร์ ND Cinema ND 4\"x5.65\"",
    specs: [],
    includes: ["Neewer Mini Matte Box PG002", "ชุดฟิลเตอร์ ND"],
  },
  {
    id: "smallrig-ad01-tripod",
    name: "SmallRig AD-01 Tripod",
    brandId: "smallrig",
    categoryId: "tripod",
    pricePerDay: 200,
    deposit: 0,
    image: "/products/smallrig-ad01-tripod.jpg",
    rating: 4.6,
    reviewCount: 0,
    available: true,
    published: true,
    description: "ขาตั้งกล้อง SmallRig AD-01 มั่นคง รองรับหัวฟลูอิด",
    specs: [],
    includes: [],
  },
  {
    id: "motorola-c1mini-single",
    name: "Motorola C1 Mini Walkie-Talkie (เดี่ยว)",
    brandId: "motorola",
    categoryId: "communication",
    pricePerDay: 100,
    deposit: 0,
    image: "/products/motorola-c1mini-single.jpg",
    rating: 4.5,
    reviewCount: 0,
    available: true,
    published: true,
    description: "วิทยุสื่อสาร Motorola C1 Mini 1 เครื่อง",
    specs: [],
    includes: ["วิทยุสื่อสาร x1"],
  },
  {
    id: "motorola-c1mini-4pcs-set",
    name: "Motorola C1 Mini Walkie-Talkie (เซ็ต 4 เครื่อง)",
    brandId: "motorola",
    categoryId: "communication",
    pricePerDay: 400,
    deposit: 0,
    image: "/products/motorola-c1mini-4pcs-set.jpg",
    rating: 4.6,
    reviewCount: 0,
    available: true,
    published: true,
    description: "วิทยุสื่อสาร Motorola C1 Mini เซ็ต 4 เครื่อง พร้อมแท่นชาร์จ",
    specs: [],
    includes: ["วิทยุสื่อสาร x4", "แท่นชาร์จ"],
  },
  {
    id: "wireless-follow-focus-set",
    name: "Wireless Follow Focus Set (Tilta Nucleus-M + V-Mount + Atomos Shinobi 7)",
    brandId: "tilta",
    categoryId: "rig-accessory",
    pricePerDay: 1200,
    deposit: 0,
    image: "/products/wireless-follow-focus-set.jpg",
    rating: 4.8,
    reviewCount: 0,
    available: true,
    published: true,
    description: "ชุด Follow Focus ไร้สาย Tilta Nucleus-M พร้อมแบตเตอรี่ V-mount และจอมอนิเตอร์ Atomos Shinobi 7",
    specs: [],
    includes: ["Tilta Nucleus-M", "แบตเตอรี่ V-mount", "จอมอนิเตอร์ Atomos Shinobi 7"],
  },
  {
    id: "hollyland-vcore",
    name: "Hollyland Vcore",
    brandId: "hollyland",
    categoryId: "monitor",
    pricePerDay: 350,
    deposit: 0,
    image: "/products/hollyland-vcore.jpg",
    rating: 4.7,
    reviewCount: 0,
    available: true,
    published: true,
    description: "อุปกรณ์ส่งสัญญาณภาพไร้สาย Hollyland Vcore เปลี่ยนมือถือเป็นจอมอนิเตอร์ 4K แบบ Real-time",
    specs: [
      { label: "ความละเอียดสูงสุด", value: "4K30 / 1080p60" },
      { label: "รองรับอุปกรณ์รับสัญญาณ", value: "สูงสุด 4 เครื่อง" },
    ],
    includes: [],
  },
];

const bundlesData = [
  {
    id: "amaran-full-light-set",
    name: "Amaran Full Light Set",
    brandId: "amaran",
    categoryId: "bundle-set",
    pricePerDay: 1200,
    deposit: 0,
    image: "/products/amaran-full-light-set.jpg",
    rating: 4.9,
    reviewCount: 0,
    available: true,
    published: true,
    description: "ชุดไฟครบชุด Amaran 300c, 150c, 60x-S พร้อม Nanlite Pavotube x2 ขาตั้งไฟและขาตั้ง C, Softbox ครบชุด",
    items: [
      { productId: "amaran-300c-set", quantity: 1, note: null },
      { productId: "amaran-150c-set", quantity: 1, note: null },
      { productId: "amaran-60xs-set", quantity: 1, note: null },
      { productId: "nanlite-pavotube-2tube-set", quantity: 1, note: null },
    ],
  },
  {
    id: "set-s-camera-sony-fx30",
    name: "SET S CAMERA SONY FX30",
    brandId: "sony",
    categoryId: "bundle-set",
    pricePerDay: 1500,
    deposit: 0,
    image: "/products/set-s-camera-sony-fx30.jpg",
    rating: 4.8,
    reviewCount: 0,
    available: true,
    published: true,
    description: "ชุดกล้อง Sony FX30 พร้อมเลนส์ 1 ตัว (เลือกได้) และกิมบอล DJI Ronin RSC2 Pro",
    items: [
      { productId: "sony-fx30-body", quantity: 1, note: null },
      { productId: "dji-ronin-rsc2-pro", quantity: 1, note: null },
      { productId: "sirui-sniper-1lens", quantity: 1, note: "เลือก 1 ชิ้น" },
      { productId: "samyang-af-35-1.8", quantity: 1, note: "เลือก 1 ชิ้น" },
      { productId: "viltrox-af-9-2.8", quantity: 1, note: "เลือก 1 ชิ้น" },
    ],
  },
  {
    id: "set-m-camera-sony-fx30",
    name: "SET M CAMERA SONY FX30",
    brandId: "sony",
    categoryId: "bundle-set",
    pricePerDay: 2200,
    deposit: 0,
    image: "/products/set-m-camera-sony-fx30.jpg",
    rating: 4.9,
    reviewCount: 0,
    available: true,
    published: true,
    description: "ชุดกล้อง Sony FX30 พร้อมเลนส์ซีนีม่า SIRUI 3 ตัว (24/35/56 T1.2), ริก Tilta, จอมอนิเตอร์, กิมบอล และขาตั้งกล้อง",
    items: [
      { productId: "sony-fx30-body", quantity: 1, note: null },
      { productId: "sirui-nightwalker-3lens-set", quantity: 1, note: null },
      { productId: "tilta-set-rig", quantity: 1, note: null },
      { productId: "feelworld-f5-pro-v4", quantity: 1, note: null },
      { productId: "dji-ronin-rsc2-pro", quantity: 1, note: null },
      { productId: "smallrig-ad01-tripod", quantity: 1, note: null },
    ],
  },
  {
    id: "set-l-camera-sony-fx30",
    name: "SET L CAMERA SONY FX30 [Full Set]",
    brandId: "sony",
    categoryId: "bundle-set",
    pricePerDay: 2990,
    deposit: 0,
    image: "/products/set-l-camera-sony-fx30.jpg",
    rating: 4.9,
    reviewCount: 0,
    available: true,
    published: true,
    description: "ชุดกล้อง Sony FX30 เต็มรูปแบบ: เลนส์ซีนีม่า SIRUI 3 ตัว, ริก, จอมอนิเตอร์, กิมบอล, ขาตั้งกล้อง, แบตเตอรี่ V-mount, Matte Box + ฟิลเตอร์ ND และ Follow Focus",
    items: [
      { productId: "sony-fx30-body", quantity: 1, note: null },
      { productId: "sirui-nightwalker-3lens-set", quantity: 1, note: null },
      { productId: "tilta-set-rig", quantity: 1, note: null },
      { productId: "feelworld-f5-pro-v4", quantity: 1, note: null },
      { productId: "dji-ronin-rsc2-pro", quantity: 1, note: null },
      { productId: "smallrig-ad01-tripod", quantity: 1, note: null },
      { productId: "smallrig-vmount-vb99", quantity: 1, note: null },
      { productId: "neewer-matte-box-nd-kit", quantity: 1, note: null },
      { productId: "tilta-mini-follow-focus", quantity: 1, note: null },
    ],
  },
  {
    id: "set-pro-sony-fx30",
    name: "SET PRO SONY FX30",
    brandId: "sony",
    categoryId: "bundle-set",
    pricePerDay: 3890,
    deposit: 0,
    image: "/products/set-pro-sony-fx30.jpg",
    rating: 5,
    reviewCount: 0,
    available: true,
    published: true,
    description: "ชุดกล้อง Sony FX30 ระดับโปรครบทุกอุปกรณ์ รวม Wireless Follow Focus Tilta Nucleus-M และจอมอนิเตอร์ Atomos Shinobi 7 เพิ่มผู้ช่วยกล้อง (Q) +1,500 บาท/วัน",
    items: [
      { productId: "sony-fx30-body", quantity: 1, note: null },
      { productId: "sirui-nightwalker-3lens-set", quantity: 1, note: null },
      { productId: "tilta-set-rig", quantity: 1, note: null },
      { productId: "feelworld-f5-pro-v4", quantity: 1, note: null },
      { productId: "dji-ronin-rsc2-pro", quantity: 1, note: null },
      { productId: "smallrig-ad01-tripod", quantity: 1, note: null },
      { productId: "smallrig-vmount-vb99", quantity: 1, note: null },
      { productId: "neewer-matte-box-nd-kit", quantity: 1, note: null },
      { productId: "tilta-mini-follow-focus", quantity: 1, note: null },
      { productId: "wireless-follow-focus-set", quantity: 1, note: null },
    ],
  },
  {
    id: "set-camera-sony-a6600",
    name: "SET CAMERA SONY A6600",
    brandId: "sony",
    categoryId: "bundle-set",
    pricePerDay: 1000,
    deposit: 0,
    image: "/products/set-camera-sony-a6600.jpg",
    rating: 4.7,
    reviewCount: 0,
    available: true,
    published: true,
    description: "ชุดกล้อง Sony A6600 พร้อมเลนส์ 1 ตัว (เลือกได้) และกิมบอล DJI Ronin RSC2 Pro",
    items: [
      { productId: "sony-a6600", quantity: 1, note: null },
      { productId: "dji-ronin-rsc2-pro", quantity: 1, note: null },
      { productId: "sirui-sniper-1lens", quantity: 1, note: "เลือก 1 ชิ้น" },
      { productId: "samyang-af-35-1.8", quantity: 1, note: "เลือก 1 ชิ้น" },
      { productId: "viltrox-af-9-2.8", quantity: 1, note: "เลือก 1 ชิ้น" },
    ],
  },
];

const settingsData = {
  id: "singleton",
  shopName: "Plu For Rent",
  logoImage: "/products/logo-plu.jpg",
  instagramHandle: "Plu_for_rent",
  contactPhone: "063-416-9115",
  contactPerson: "คุณจู",
  footerTagline: "บริการเช่ากล้อง เลนส์ซีนีม่า และอุปกรณ์ถ่ายภาพ/วิดีโอ ครบ จบ ในที่เดียว ส่งไว ราคาเป็นมิตร",
  businessHoursLine1: "จันทร์ - ศุกร์: 09:00 - 19:00",
  businessHoursLine2: "เสาร์ - อาทิตย์: 10:00 - 18:00",
  metaTitle: "Plu For Rent — เช่ากล้องและอุปกรณ์ถ่ายภาพ/วิดีโอ",
  metaDescription: "บริการเช่ากล้อง เลนส์ซีนีม่า และอุปกรณ์ถ่ายภาพ/วิดีโอ โดย Plu For Rent",

  heroEyebrow: "เช่าง่าย ส่งไว ราคาเป็นมิตร",
  heroTitleLine1: "เช่ากล้องถ่ายภาพ",
  heroTitleLine2: "ครบทุกความต้องการ",
  heroSubheading: "เลือกกล้อง เลนส์ และอุปกรณ์เสริมจากแบรนด์ชั้นนำ จองผ่าน LINE หรือฟอร์มออนไลน์ ได้รับสินค้าไว ไม่ยุ่งยาก",
  heroSearchPlaceholder: "ค้นหากล้อง, เลนส์, ยี่ห้อ...",
  popularSearchLabel: "ค้นหายอดนิยม:",
  popularSearchTags: ["Sony A7 IV", "Canon R6", "GoPro", "DJI Air 3"],

  categoriesHeading: "เลือกตามหมวดหมู่",
  categoriesSubheading: "อุปกรณ์ครบทุกประเภทงานถ่ายภาพ",
  brandsHeading: "เลือกตามยี่ห้อ",
  brandsSubheading: "แบรนด์กล้องชั้นนำที่คุณไว้วางใจ",
  featuredHeading: "สินค้าแนะนำ",
  featuredSubheading: "ยอดนิยมประจำเดือนนี้",
};

async function main() {
  await prisma.bundleItem.deleteMany();
  await prisma.bundle.deleteMany();
  await prisma.product.deleteMany();
  await prisma.brand.deleteMany();
  await prisma.category.deleteMany();

  for (const c of categoriesData) {
    await prisma.category.upsert({ where: { id: c.id }, update: {}, create: c });
  }
  for (const b of brandsData) {
    await prisma.brand.upsert({ where: { id: b.id }, update: {}, create: b });
  }
  for (const p of productsData) {
    await prisma.product.upsert({ where: { id: p.id }, update: {}, create: p });
  }

  let bundleItemCount = 0;
  for (const bundle of bundlesData) {
    const { items, ...bundleData } = bundle;
    await prisma.bundle.upsert({ where: { id: bundleData.id }, update: {}, create: bundleData });
    for (const item of items) {
      await prisma.bundleItem.upsert({
        where: { bundleId_productId: { bundleId: bundle.id, productId: item.productId } },
        update: {},
        create: { bundleId: bundle.id, productId: item.productId, quantity: item.quantity, note: item.note },
      });
      bundleItemCount++;
    }
  }

  await prisma.siteSettings.upsert({
    where: { id: "singleton" },
    update: {},
    create: settingsData,
  });

  console.log(
    `Seeded ${categoriesData.length} categories, ${brandsData.length} brands, ${productsData.length} products, ${bundlesData.length} bundles, ${bundleItemCount} bundle items, 1 site settings row.`,
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
